# https://www.comet.ml

comet:
  _target_: pytorch_lightning.loggers.comet.CometLogger
  api_key: ${oc.env:COMET_API_KEY} # api key is loaded from environment variable
  project_name: "mnist"
  experiment_name: ${name}
