_target_: cloudmask.datamodules.MNISTDataModule
data_dir: ${data_dir} # data_dir is specified in config.yaml
train_val_test_split: [55_000, 5_000, 10_000]
batch_size: 64
num_workers: 0
pin_memory: False
persistent_workers: False
