name: Lint

on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - uses: pre-commit/action@v2.0.0
